@startuml


Class ParkingBoy << Entity >> {
  List<ParkingLot> parkingLots

  + Ticket park(Car car)

  + void setParkingLots (ParkingLot[] parkingLots)
  + List<ParkingLot> getParkingLots()
}


class ParkingLot << Entity >> {
  String serialNumber
  int capacity 
  int sortIndex;
  + Ticket park(Car car)
}


Class Car << Value Object >> {
    String plateNumber
}

Class Ticket << Value Object >> {
  String carPlateNumber;
  String parkingLotSerialNumber;
}

Ticket "1" *--> "1" Car
ParkingLot "1" o--> "0..many" Ticket
ParkingBoy "1" o--> "0..many" ParkingLot




@enduml
